configuration: Release
version: 1.0.0.{build}

before_build:
  - nuget restore

build:
  project: csharp-metar-display.sln
  verbosity: minimal

after_build:
  - ps: nuget pack csharp-metar-display\csharp-metar-display.nuspec -Version $env:APPVEYOR_BUILD_VERSION

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: i6qLx3fbNFssWZaO97vPZw3lXDoeYPLHzliqLKw1F5vthfEX6gq7eu2qJxxKrCqF

after_test:
  - nuget install NUnit.Runners -Version 3.8.0
  - nuget install OpenCover -Version 4.6.519
  - nuget install coveralls.net -Version 0.412
  - OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:"--result nunit2 csharp-metar-display.tests\bin\Release\csharp-metar-display.tests.dll" -returntargetcode:10000 -log:All -filter:"+[csharp-metar-display]* -[csharp-metar-display.tests*]*" -register:Path32 -output:".\cover_results.xml"
  - coveralls.net.0.412\tools\csmacnz.Coveralls.exe --opencover -i .\cover_results.xml

artifacts:
  - path: '**\csharp-metar-display.*.nupkg'

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: zgNT2DNyLuvf8sH+Y1kAI/aOL6E4S5zVHeadTWSFP1/vxVpEQ75QLxyBQMZr4A0n
  skip_symbols: true
